packages:
  - "."

overrides:
  "@lhci/cli>tmp": 0.2.7
  "@lhci/cli>uuid": 11.1.1
  "@sveltejs/kit>cookie": 0.7.2
  "external-editor>tmp": 0.2.7

minimumReleaseAgeExclude:
  - miniflare@4.20260722.0
  - "@cloudflare/vitest-pool-workers@0.18.8"
  - wrangler@4.114.0

storeDir: .pnpm-store
confirmModulesPurge: false

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
