// @ts-ignore -- this JavaScript adapter output is generated by `pnpm build` immediately before Wrangler bundles this entrypoint.
import svelteWorker from "./.svelte-kit/cloudflare/_worker.js";
import { WorkerEntrypoint } from "cloudflare:workers";

import { cacheTagsForPath } from "./src/lib/published";
import { publicCachePolicy } from "./src/lib/server/cache-policy";
import { canonicalRedirect } from "./src/lib/server/canonical-origin";
import { PublishWorkflow } from "./src/lib/server/content/publish-workflow";

export { PublishWorkflow };

export default class PublicWorker extends WorkerEntrypoint<Env> {
  async fetch(request: Request): Promise<Response> {
    const env = this.env;
    const ctx = this.ctx;
    const incomingUrl = new URL(request.url);
    const canonicalOrigin = new URL(env.APP_ORIGIN);
    const destination = canonicalRedirect(request.url, env.APP_ORIGIN, env.ENVIRONMENT);
    if (destination) {
      return new Response(null, {
        status: 308,
        headers: {
          "cache-control": "public, max-age=3600",
          location: destination,
        },
      });
    }
    const canonicalRequest =
      incomingUrl.origin === canonicalOrigin.origin
        ? request
        : new Request(
            new URL(`${incomingUrl.pathname}${incomingUrl.search}`, canonicalOrigin),
            request,
          );
    const resolved = await svelteWorker.fetch(canonicalRequest, env, ctx);
    const response = new Response(resolved.body, resolved);
    if (response.headers.get("x-public-cache") === "1") {
      const pathname = new URL(request.url).pathname;
      const policy = publicCachePolicy(pathname);
      response.headers.delete("x-public-cache");
      response.headers.set("cache-control", policy.browser);
      response.headers.set("cloudflare-cdn-cache-control", policy.edge);
      response.headers.set("cache-tag", cacheTagsForPath(pathname).join(","));
    }
    return response;
  }

  async purgePublicCache(options: CachePurgeOptions): Promise<CachePurgeResult> {
    if (!this.ctx.cache) throw new Error("Workers cache purge context is unavailable");
    return this.ctx.cache.purge(options);
  }
}
