// @ts-ignore -- this JavaScript adapter output is generated by `pnpm build` immediately before Wrangler bundles this entrypoint.
import svelteWorker from "./.svelte-kit/cloudflare/_worker.js";
import { WorkerEntrypoint } from "cloudflare:workers";

import { cacheTagsForPath } from "./src/lib/published";
import { publicCachePolicy } from "./src/lib/server/cache-policy";
import { normalizeWorkersDevRequestProtocol } from "./src/lib/server/cloudflare-request";
import { PublishWorkflow } from "./src/lib/server/content/publish-workflow";

export { PublishWorkflow };

export default class PublicWorker extends WorkerEntrypoint<Env> {
  async fetch(request: Request): Promise<Response> {
    const env = this.env;
    const ctx = this.ctx;
    const applicationRequest = normalizeWorkersDevRequestProtocol(request);
    const incomingUrl = new URL(applicationRequest.url);
    const canonicalOrigin = new URL(env.APP_ORIGIN);
    if (
      incomingUrl.hostname === "www.aamirazad.com" &&
      canonicalOrigin.hostname === "aamirazad.com" &&
      isPrivatePath(incomingUrl.pathname)
    ) {
      return new Response(null, {
        status: 307,
        headers: {
          "cache-control": "private, no-store",
          location: new URL(`${incomingUrl.pathname}${incomingUrl.search}`, canonicalOrigin).href,
        },
      });
    }
    const resolved = await svelteWorker.fetch(applicationRequest, env, ctx);
    const response = new Response(resolved.body, resolved);
    if (response.headers.get("x-public-cache") === "1") {
      const pathname = incomingUrl.pathname;
      const policy = publicCachePolicy(pathname);
      response.headers.delete("x-public-cache");
      response.headers.set("cache-control", policy.browser);
      response.headers.set("cloudflare-cdn-cache-control", policy.edge);
      response.headers.set("cache-tag", cacheTagsForPath(pathname).join(","));
    }
    return response;
  }

  async purgePublicCache(options: CachePurgeOptions): Promise<CachePurgeResult> {
    if (!this.ctx.cache) throw new Error("Workers cache purge context is unavailable");
    return this.ctx.cache.purge(options);
  }
}

function isPrivatePath(pathname: string): boolean {
  return ["/admin", "/api", "/auth", "/preview"].some(
    (prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`),
  );
}
